### ISSUE TITLE
Can't download directly from Android device 

### ISSUE THREAD

**Issue by incIined** [morla10111/sharkle#1]
Galaxy S9+ 8.0, Feb security patch, using Samsung Internet browser 

When opening 
`https://github.com/morla10111/sharkle/blob/master/app/release/app-release.apk` 
, it gives me a  "This file is too big to show. Sorry!" and doesn't show me a download button. 

Image of issue:
![](https://i.imgur.com/bcQHaWI.jpg)

**Comment by morla10111** [comment]
Hey,

you can try to click on the `Desktop version` link. The download should then work.

Regards,
morla
